import { type FormEvent, useState } from 'react';
import type { BidInput } from './bidding-client';
import { localInputToIso } from './datetime';
import { fuelGrades, type ActiveBuyer, type FuelGrade } from './types';

type Row = { grade: FuelGrade; quantity: string };
const emptyRows = (): Row[] => [{ grade: 'vlsfo', quantity: '' }];

export function FuelRows({ rows, onChange, disabled }: { rows: Row[]; onChange: (rows: Row[]) => void; disabled: boolean }) {
  const replace = (index: number, row: Row) => onChange(rows.map((candidate, candidateIndex) => candidateIndex === index ? row : candidate));
  return <fieldset><legend>Fuel items</legend>{rows.map((row, index) => <div className="fuel-row" key={`${row.grade}-${index}`}><label>Grade<select aria-label={`Fuel grade ${index + 1}`} disabled={disabled} value={row.grade} onChange={(event) => replace(index, { ...row, grade: event.target.value as FuelGrade })}>{fuelGrades.map((grade) => <option disabled={rows.some((candidate, candidateIndex) => candidateIndex !== index && candidate.grade === grade)} value={grade} key={grade}>{grade.toUpperCase()}</option>)}</select></label><label>Quantity MT<input aria-label={`Fuel quantity ${index + 1}`} type="number" min="0.01" step="any" required disabled={disabled} value={row.quantity} onChange={(event) => replace(index, { ...row, quantity: event.target.value })} /></label>{rows.length > 1 ? <button type="button" className="secondary" disabled={disabled} onClick={() => onChange(rows.filter((_, candidateIndex) => candidateIndex !== index))}>Remove fuel</button> : null}</div>)}{rows.length < fuelGrades.length ? <button type="button" className="secondary" disabled={disabled} onClick={() => { const grade = fuelGrades.find((candidate) => !rows.some((row) => row.grade === candidate)); if (grade) onChange([...rows, { grade, quantity: '' }]); }}>Add fuel</button> : null}</fieldset>;
}

export function CreateBidForm({ buyers, disabled, onSubmit }: { buyers: ActiveBuyer[]; disabled: boolean; onSubmit: (input: BidInput) => Promise<boolean> }) {
  const [rows, setRows] = useState<Row[]>(emptyRows); const [vessel, setVessel] = useState(''); const [port, setPort] = useState(''); const [window, setWindow] = useState(''); const [deadline, setDeadline] = useState(''); const [responsible, setResponsible] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const quantities = rows.map((row) => Number(row.quantity)); if (rows.some((row, index) => !row.quantity || !Number.isFinite(quantities[index]) || quantities[index]! <= 0)) return; const succeeded = await onSubmit({ vesselVoyage: vessel, portName: port, deliveryWindow: window, deadlineAt: localInputToIso(deadline), responsibleBuyerUserId: responsible || null, fuelGrades: rows.map((row) => row.grade), quantities }); if (succeeded) { setRows(emptyRows()); setVessel(''); setPort(''); setWindow(''); setDeadline(''); setResponsible(''); } };
  return <details className="panel"><summary>Create bid</summary><form className="operation-form" onSubmit={(event) => void submit(event)}><label>Vessel / voyage<input required disabled={disabled} value={vessel} onChange={(event) => setVessel(event.target.value)} /></label><label>Port<input required disabled={disabled} value={port} onChange={(event) => setPort(event.target.value)} /></label><label>Delivery window<input required disabled={disabled} value={window} onChange={(event) => setWindow(event.target.value)} /></label><label>Deadline<input aria-label="Create deadline" type="datetime-local" disabled={disabled} value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label><label>Responsible BUYER<select disabled={disabled} value={responsible} onChange={(event) => setResponsible(event.target.value)}><option value="">Current actor</option>{buyers.map((buyer) => <option value={buyer.user_id} key={buyer.user_id}>{buyer.display_label}</option>)}</select></label><FuelRows rows={rows} onChange={setRows} disabled={disabled} /><button type="submit" disabled={disabled}>Create bid</button></form></details>;
}
