import { type FormEvent, useCallback, useEffect, useState } from 'react';
import type { AccessClient, AccessSession } from './access-client';
import type { BiddingClient } from '../bidding/bidding-client';
import type { SellerRegistrationRequest, WorkflowError } from '../bidding/types';
import type { RealtimeInvalidationClient } from '../realtime/realtime-client';

// This pure flag parser is intentionally colocated with its only presentation consumers.
// eslint-disable-next-line react-refresh/only-export-components
export function sellerRegistrationEnabled(value: string | undefined): boolean { return value === 'true'; }
type Notice = { kind: 'error' | 'success'; text: string };
const genericError = 'The request could not be completed. Please try again.';

export function PublicSellerRegistration({ client, onBack, onInviteVerified }: { client: AccessClient; onBack: () => void; onInviteVerified?: () => void }) {
  const [mode, setMode] = useState<'menu' | 'signup' | 'invite' | 'invite-password'>('menu');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [code, setCode] = useState(''); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice | null>(null);
  const resetSecrets = () => { setPassword(''); setConfirmation(''); setCode(''); };
  const signup = async (event: FormEvent) => {
    event.preventDefault(); if (!password || password !== confirmation) { setNotice({ kind: 'error', text: password ? 'Passwords do not match.' : 'Enter and confirm your password.' }); return; }
    setPending(true); setNotice(null); const result = await client.signUpSeller(email, password); resetSecrets(); setPending(false);
    setNotice(result.error ? { kind: 'error', text: genericError } : { kind: 'success', text: 'Check your email to confirm your address, then return to sign in.' });
  };
  const verifyInvite = async (event: FormEvent) => {
    event.preventDefault(); if (!/^\d{6}$/.test(code)) { setNotice({ kind: 'error', text: 'Enter the 6-digit invitation code.' }); return; }
    setPending(true); setNotice(null); const result = await client.verifySellerInvite(email, code); setCode(''); setPending(false);
    if (result.error) { setNotice({ kind: 'error', text: genericError }); return; }
    onInviteVerified?.(); setMode('invite-password');
  };
  const setupPassword = async (event: FormEvent) => {
    event.preventDefault(); if (!password || password !== confirmation) { setNotice({ kind: 'error', text: password ? 'Passwords do not match.' : 'Enter and confirm your password.' }); return; }
    setPending(true); setNotice(null); const result = await client.updatePassword(password); resetSecrets(); setPending(false);
    if (result.error) { setNotice({ kind: 'error', text: 'Password could not be updated. Please try again.' }); return; }
    await client.signOut(); onBack();
  };
  if (mode === 'menu') return <section className="panel auth-panel" aria-labelledby="seller-options-heading"><p className="eyebrow">SELLER candidate access</p><h1 id="seller-options-heading">Create or activate a SELLER account</h1><p className="lede">Account enrollment does not grant application access. A BUYER approves and maps eligible candidates to an existing SELLER organization.</p><div className="button-row"><button type="button" onClick={() => { setNotice(null); setMode('signup'); }}>Create SELLER account</button><button type="button" className="secondary" onClick={() => { setNotice(null); setMode('invite'); }}>Use invitation code</button><button type="button" className="secondary" onClick={onBack}>Back to sign in</button></div></section>;
  if (mode === 'signup') return <section className="panel auth-panel" aria-labelledby="seller-signup-heading"><p className="eyebrow">SELLER candidate access</p><h1 id="seller-signup-heading">Create SELLER account</h1><p className="lede">This creates only an account for review; it does not choose a company or grant a BUYER role.</p><form className="auth-form" onSubmit={(event) => void signup(event)}><label>Email<input type="email" autoComplete="email" required disabled={pending} value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" autoComplete="new-password" required disabled={pending} value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Confirm password<input type="password" autoComplete="new-password" required disabled={pending} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label>{notice ? <p className={`notice ${notice.kind}`} role={notice.kind === 'error' ? 'alert' : 'status'}>{notice.text}</p> : null}<button type="submit" disabled={pending}>{pending ? 'Creating account…' : 'Create SELLER account'}</button><button type="button" className="secondary" disabled={pending} onClick={() => { resetSecrets(); setMode('menu'); }}>Back</button></form></section>;
  if (mode === 'invite') return <section className="panel auth-panel" aria-labelledby="seller-invite-heading"><p className="eyebrow">SELLER invitation</p><h1 id="seller-invite-heading">Use invitation code</h1><form className="auth-form" onSubmit={(event) => void verifyInvite(event)}><label>Email<input type="email" autoComplete="email" required disabled={pending} value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>6-digit invitation code<input inputMode="numeric" autoComplete="one-time-code" pattern="\d{6}" maxLength={6} required disabled={pending} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} /></label>{notice ? <p className={`notice ${notice.kind}`} role="alert">{notice.text}</p> : null}<button type="submit" disabled={pending}>{pending ? 'Verifying…' : 'Verify invitation'}</button><button type="button" className="secondary" disabled={pending} onClick={() => { resetSecrets(); setMode('menu'); }}>Back</button></form></section>;
  return <section className="panel auth-panel" aria-labelledby="seller-invite-password-heading"><p className="eyebrow">SELLER invitation</p><h1 id="seller-invite-password-heading">Set your password</h1><p className="lede">Setting a password does not open a workspace. Access remains server-verified.</p><form className="auth-form" onSubmit={(event) => void setupPassword(event)}><label>New password<input type="password" autoComplete="new-password" required disabled={pending} value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Confirm new password<input type="password" autoComplete="new-password" required disabled={pending} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label>{notice ? <p className={`notice ${notice.kind}`} role="alert">{notice.text}</p> : null}<button type="submit" disabled={pending}>{pending ? 'Saving…' : 'Save password'}</button><button type="button" className="secondary" disabled={pending} onClick={() => void client.signOut().then(onBack)}>Sign out</button></form></section>;
}

export function SellerCandidateRegistration({ session, client, biddingClient, realtimeClient, recheckAccess, invitePasswordRequired = false, onInvitePasswordDone }: { session: AccessSession; client: AccessClient; biddingClient: BiddingClient; realtimeClient?: RealtimeInvalidationClient; recheckAccess: () => void; invitePasswordRequired?: boolean; onInvitePasswordDone?: () => void }) {
  const [request, setRequest] = useState<SellerRegistrationRequest | null | undefined>(undefined); const [name, setName] = useState(''); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice | null>(null); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState('');
  const load = useCallback(async () => { setPending(true); let result; try { result = biddingClient.getMySellerRegistrationRequest ? await biddingClient.getMySellerRegistrationRequest() : { data: null, error: { kind: 'protocol' } as WorkflowError }; } catch { result = { data: null, error: { kind: 'protocol' } as WorkflowError }; } setPending(false); if (result.error) { setRequest(undefined); setNotice({ kind: 'error', text: 'Registration status could not be verified. No access has been opened.' }); return; } setRequest(result.data); }, [biddingClient]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => realtimeClient?.subscribeToAccessInvalidations(session.userId, () => { void load(); recheckAccess(); }), [load, realtimeClient, recheckAccess, session.userId]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const normalized = name.trim(); if (!normalized || normalized.length > 120) { setNotice({ kind: 'error', text: 'Enter an organization name of up to 120 characters.' }); return; } setPending(true); setNotice(null); const result = biddingClient.submitSellerRegistrationRequest ? await biddingClient.submitSellerRegistrationRequest(normalized) : { data: null, error: { kind: 'protocol' } as WorkflowError }; setPending(false); if (result.error || !result.data) { setNotice({ kind: 'error', text: genericError }); return; } setName(''); setRequest(result.data); };
  const setupInvitePassword = async (event: FormEvent) => { event.preventDefault(); if (!password || password !== confirmation) { setNotice({ kind: 'error', text: password ? 'Passwords do not match.' : 'Enter and confirm your password.' }); return; } setPending(true); const result = await client.updatePassword(password); setPassword(''); setConfirmation(''); setPending(false); if (result.error) { setNotice({ kind: 'error', text: 'Password could not be updated. Please try again.' }); return; } await client.signOut(); onInvitePasswordDone?.(); };
  if (invitePasswordRequired) return <section className="panel status-panel"><h1>Set your password</h1><p className="lede">Invitation verification did not open a workspace. Set a password, then sign in again.</p><form className="auth-form" onSubmit={(event) => void setupInvitePassword(event)}><label>New password<input type="password" autoComplete="new-password" required disabled={pending} value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Confirm new password<input type="password" autoComplete="new-password" required disabled={pending} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label>{notice ? <p className="notice error" role="alert">{notice.text}</p> : null}<button type="submit" disabled={pending}>Save password</button><button type="button" className="secondary" disabled={pending} onClick={() => void client.signOut()}>Sign out</button></form></section>;
  if (request === undefined) return <section className="panel status-panel"><p className="eyebrow">SELLER candidate</p><h1>Registration status unavailable</h1><p className="lede">No workspace has been opened.</p><div className="button-row"><button type="button" onClick={() => void load()} disabled={pending}>Retry status check</button><button type="button" className="secondary" onClick={() => void client.signOut()}>Sign out</button></div></section>;
  if (request?.status === 'pending') return <section className="panel status-panel"><p className="eyebrow">SELLER candidate</p><h1>Pending BUYER approval</h1><p>Requested organization: {request.requested_organization_name}</p><p>Source: {request.source}</p><p>Submitted: {new Date(request.submitted_at).toLocaleString()}</p><button type="button" className="secondary" onClick={() => void client.signOut()}>Sign out</button></section>;
  if (request?.status === 'approved') return <section className="panel status-panel"><p className="eyebrow">SELLER candidate</p><h1>Approval recorded but no active access is available</h1><p className="lede">No workspace has been opened. Retry server access verification or sign out.</p><div className="button-row"><button type="button" onClick={recheckAccess}>Retry access verification</button><button type="button" className="secondary" onClick={() => void client.signOut()}>Sign out</button></div></section>;
  return <section className="panel status-panel"><p className="eyebrow">SELLER candidate</p><h1>{request?.status === 'rejected' ? 'Registration was not approved' : 'Request SELLER registration'}</h1><p className="lede">Your organization name is a review hint only. A BUYER selects an existing SELLER organization if approval is granted.</p><form className="auth-form" onSubmit={(event) => void submit(event)}><label>Organization / company name<input maxLength={120} required disabled={pending} value={name} onChange={(event) => setName(event.target.value)} /></label>{notice ? <p className="notice error" role="alert">{notice.text}</p> : null}<button type="submit" disabled={pending}>{request?.status === 'rejected' ? 'Submit new request' : 'Submit registration request'}</button><button type="button" className="secondary" disabled={pending} onClick={() => void client.signOut()}>Sign out</button></form></section>;
}
